version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ipo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ipo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ipo-network

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipo-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ipo_db
      DB_USERNAME: root
      DB_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ipo-network

# Volumes
volumes:
  mysql-data:
    driver: local

# Networks
networks:
  ipo-network:
    driver: bridge 